### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by the-homeless-god** [ReEngine/reengine.github.io#3]
- move `Stylesheets/style.css` to `public/style.css`
- avoid `*` in `style.css`
- format `style.css` file with `prettier`, it can be `npx prettier --write public/style.css`
- put common part of `.image` and `.blur` to the definition like the following:

```css
.image {
    z-index: 1; 
}

.blur {
    filter: blur(10vh);
}

.image, .blur {
    grid-column: 1/span 8;
    grid-row: 1; 
    max-height: 100vh;
    margin: auto;  
}
```

- move `resources/*` to `public/assets/*`
- move `public/assets/pictures` to `public/assets/images`
- move `public/assets/scripts` to `public/assets/js`
- rename `GetImage.js` to `image.js`
- rewrite content of `image.js` to using of latest version for ES (ECMAScript) and don't forget to format code
- format content of `index.html`
- rename `github-actions-demo.yml` to `deploy-static.yml`
